version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3696:3696"
    environment:
      - REACT_APP_BACKEND_URL=https://shop-ease-umber-nu.vercel.app
      - PORT=3696
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
    volumes:
      - ./server:/app
      - /app/node_modules
    stdin_open: true
    tty: true